default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV["DB_HOST"] %>
  username: <%= ENV["DB_USER"] %>
  password: <%= ENV["DB_PASSWORD"] %>

development:
  primary: &primary_development
    <<: *default
    database: app_development
  cache:
    <<: *primary_development
    database: app_development_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_development
    database: app_development_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_development
    database: app_development_cable
    migrations_paths: db/cable_migrate

test:
  primary: &primary_test
    <<: *default
    database: app_test
  cache:
    <<: *primary_test
    database: app_test_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_test
    database: app_test_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_test
    database: app_test_cable
    migrations_paths: db/cable_migrate

production:
  primary: &primary_production
    <<: *default
    database: app_production
  cache:
    <<: *primary_production
    database: app_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: app_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: app_production_cable
    migrations_paths: db/cable_migrate
